services:
  - type: web  
    plan: free
    name: front-tribu-b-2025-2c-dev
    runtime: node
    buildCommand: 'npm install'
    startCommand: 'npm start'
    repo: https://github.com/CrissRMFI/PSA-FrontEnd.git
    branch: 'develop'
    autoDeployTrigger: commit
    envVars:
      - key: SUPPORT_MODULE_BACKEND_URL
        value: https://app-modulo-soporte-dev.onrender.com
      - key: PROJECT_MODULE_BACKEND_URL
        value: https://app-modulo-proyectos-dev.onrender.com
